Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: "echo Hello"
    
    config.vm.define "ansible" do |ansible|
        ansible.vm.box = "ubuntu/focal64"
        ansible.vm.network "public_network", ip: "192.168.15.100"
        ansible.vm.box_download_insecure = true
        ansible.vm.provision "shell", inline: <<-SHELL
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config 
        systemctl restart sshd.service
        SHELL
    end

    config.vm.define "linux1" do |ansible|
        ansible.vm.box = "ubuntu/focal64"
        ansible.vm.network "public_network", ip: "192.168.15.101"
        ansible.vm.box_download_insecure = true
        ansible.vm.provision "shell", inline: <<-SHELL
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd.service
        SHELL
    end

    config.vm.define "linux2" do |ansible|
        ansible.vm.box = "ubuntu/focal64"
        ansible.vm.network "public_network", ip: "192.168.15.102"
        ansible.vm.box_download_insecure = true
        ansible.vm.provision "shell", inline: <<-SHELL
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd.service
        SHELL
    end

    config.vm.define "linux3" do |ansible|
        ansible.vm.box = "ubuntu/focal64"
        ansible.vm.network "public_network", ip: "192.168.15.103"
        ansible.vm.box_download_insecure = true
        ansible.vm.provision "shell", inline: <<-SHELL
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd.service
        SHELL
    end
end
  