--- # Indica para o S.O. que se trata de arquivo Yml
- name: Update cache # "Update cache" é apenas descritivo, apt update
  apt:
    update_cache: yes

# Intalando o Nginx com módulo apt
- name: Install nginx 
  apt:
    name: nginx

# Adicionando um arquivo html de um site
- name: copy index.html
  copy:  
    src: site.html
    dest: /var/www/html