
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
   
  config.vm.define "ansible" do |ansible|
     ansible.vm.box = "ubuntu/focal64"
     ansible.vm.network "public_network", ip: "192.168.15.70"
     ansible.vm.box_download_insecure = true
     ansible.vm.provision "shell", inline: <<-SHELL
     apt update
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config 
     systemctl restart sshd.service
     SHELL
  end

  config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
        vb.name = "master"
  end

  #config.vm.box = "ubuntu/focal64"

  #config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # config.vm.network "private_network", ip: "192.168.33.10"

  #config.vm.network "public_network", ip: "192.168.15.70"

  #config.vm.synced_folder "./html", "/var/www/html"

  # config.vm.provision "shell", inline: <<-SHELL
     
  # SHELL
end
