Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  
  config.vm.define "ansible" do |ansible|
      ansible.vm.box = "ubuntu/focal64"
      ansible.vm.network "public_network", ip: "192.168.15.85"
      ansible.vm.box_download_insecure = true
      ansible.vm.provision "shell", inline: <<-SHELL
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config 
      systemctl restart sshd.service
      SHELL
  end

  config.vm.provision "shell", inline: <<-SHELL
     apt update
     apt upgrade
   SHELL
end